# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tony Jones | Product Designer
email: ad30jone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a product designer with a passion for web accessibility and application security. Come check out my thoughts, writing, and general web stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "anthonyjones.me" # the base hostname & protocol for your site
twitter_username: iamtonybagels
dribbble_username: iamtonybagels
instagram_username: iamtonybagels
github_username:  tony-jones

# Build settings
markdown: kramdown
permalink: pretty
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]

# ==================
# Collections 
# ==================
collections_dir: collection_types

collections:
  collection_types:
    output: true

collections:
  posts:
    output: true
    permalink: /blog/:title/

  projects:
    output: true
    permalink: /projects/:title/

  resources:
    output: true
    permalink: /resources/:title/

  issues:
    output: true
    permalink: /issues/:title/

